

GET http://localhost:50000/v1.0/invoke/offerservice/method/e498dab5-77b5-4f19-a6f8-51c0897dd HTTP/1.1

###

POST http://localhost:50000/v1.0/invoke/offerservice/method/ HTTP/1.1
content-type: application/json

{
  "candidateId": "candidate-id-123123",
  "firstName": "Mark",
  "lastName": "Kitz",
  "personalEmail": "test@test.ca",
  "manager": "markk",
  "competitionId": "competition-id-123123",
  "positionName": "position-name",
  "level": "20",
  "step": 3,
  "salary": 100000
}


### INVALID REQUEST

POST http://localhost:50000/v1.0/invoke/offerservice/method/ HTTP/1.1
content-type: application/json

{
  "candidateId": "candidate-id-123123",
  "firstName": "sdsdf!!!123",
  "lastName": "Kitz",
  "personalEmail": "test@test.ca",
  "manager": "markk",
  "competitionId": "competition-id"

}
###
PUT http://localhost:50000/v1.0/invoke/offerservice/method/ManagerSignOffRequested/322768b2-7425-4371-87fb-a65baf253e6c

###
PUT http://localhost:50000/v1.0/invoke/offerservice/method/ManagerSignOff/005c0c5d-92f6-47b5-9219-33048ca9c97d
content-type: application/json

{
  "approved": true
}