

GET https://localhost:3600/v1.0/state/statestore HTTP/1.1

###

POST http://localhost:50000/v1.0/invoke/offerservice/method/ HTTP/1.1
content-type: application/json

{
  "candidateId": "candidate-id",
  "firstName": "Kristi",
  "lastName": "Kitz",
  "personalEmail": "test@test.ca",
  "manager": "markk",
  "competitionId": "competition-id",
  "positionName": "position-name",
  "level": "20",
  "step": 5,
  "salary": 100000
}

###

