

GET http://localhost:50000/v1.0/invoke/offerservice/method/7a780c3e-91b2-44c3-9b64-ab249dfe751b HTTP/1.1

###

POST http://localhost:50000/v1.0/invoke/offerservice/method/ HTTP/1.1
content-type: application/json

{
  "candidateId": "candidate-id",
  "firstName": "Kristi",
  "lastName": "Kitz",
  "personalEmail": "test@test.ca",
  "manager": "markk",
  "competitionId": "competition-id",
  "positionName": "position-name",
  "level": "20",
  "step": 5,
  "salary": 100000
}

###
PUT http://localhost:50000/v1.0/invoke/offerservice/method/ManagerSignOffRequested/7a780c3e-91b2-44c3-9b64-ab249dfe751b

###
PUT http://localhost:50000/v1.0/invoke/offerservice/method/ManagerSignOff/7a780c3e-91b2-44c3-9b64-ab249dfe751b
content-type: application/json

{
  "approved":  true
}