

GET https://localhost:3600/v1.0/state/statestore HTTP/1.1

###

POST https://localhost:3600/v1.0/state/statestore HTTP/1.1
content-type: application/json

{
    "key": "hello",
    "value": "world"
}